### ISSUE TITLE
Don't get it working

### ISSUE THREAD

**Issue by Geepup** [ericvan76/send-to-webhook#3]
With below config (as in the example) I try to send something to a webhook tester. I get the "failed to fetch" message.
Please advise.

[
  {
    "name": "myslack",
    "action": {
      "url": "<https://webhook.site/72e72360-b9c6-4cdc-8d5d-a6bbd9d250e6>",
      "payload": {
        "text": "%s"
      }
    }
  }
]

**Comment by ericvan76** [comment]
There is nothing we can do if the webhook api is not reachable, please double-check its url, method and cross-origin requirements.
