### ISSUE TITLE
How do I receive the URL of the page currently looked at?

### ISSUE THREAD

**Issue by mrjcleaver** [ericvan76/send-to-webhook#5]
Seems a stupid question, but how do I receive the name of the page in context? Thanks!

**Comment by ericvan76** [comment]
Hi @mrjcleaver, that's not related to this extension, and also for the security/privacy purpose, the extension doesn't have the ability/request to read title/content of your loaded page.

**Comment by mrjcleaver** [comment]
Great, thanks for the prompt answer!
