### ISSUE TITLE
Show result?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [ericvan76/send-to-webhook#7]
Love this tool! I'm using it to send youtube videos into my watch-later, via a Heroku hobby server.

It would be cool if the extension could show a browser notification of the response from the webhook. Like if the webhook returns HTTP 200 and "Success", you could toast "Success". And also to show any errors the webhook responds with.

**Comment by ericvan76** [comment]
Thanks @GeoffreyPlitt, it's on my radar.

**Comment by GeoffreyPlitt** [comment]
@ericvan76 Cool! Any ETA? On occasion, my webhook has an error in the response and I don't know until I check logs.

**Comment by ericvan76** [comment]
@GeoffreyPlitt I'm trying to wrap up something recently before I can pull my brain back on this, shouldn't be too far.

**Comment by GeoffreyPlitt** [comment]
@ericvan76 Any update on this? I lost 30+ videos yesterday because my receiving server was sending 500 errors, but your plugin didn't show any errors, so I didn't realize for a while.

At the very least, when the webhook returns a non-2xx result, can you show an error?

**Comment by ericvan76** [comment]
@GeoffreyPlitt, Sorry I don't really have time to maintain this little thing. But you're welcome to contribute if you have spare time.
